repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: docs/CHANGELOG.md
      - id: mixed-line-ending

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.14.0
    hooks:
      - id: commitizen

  - repo: https://github.com/tho-aguillen/git-mob
    rev: v3.2.1
    hooks:
      - id: add-coauthors
        stages: ['prepare-commit-msg']
