apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Guests Team
spec:
  type: team
  profile:
    email: guests@airline.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: airline
  children: []

---

# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest1
spec:
  profile:
    displayName: Guest one
    email: guest.one@example.com
  memberOf: [group:default/guests]

---

# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest2
spec:
  profile:
    displayName: Guest two
    email: guest.two@example.com
  memberOf: [group:default/guests]
