apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: software-engineering
  description: The software engineering business domain
  tags:
    - software-engineering
spec:
  type: business-unit
  # Intentional no profile for testing
  parent: airline
  children: [platform-team]

---

apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Team
  tags:
    - software-engineering
    - platform
spec:
  type: product-area
  profile:
    # Intentional no displayName for testing
    email: platform-team@airline.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Fluffy&backgroundType=solid,gradientLinear&backgroundColor=ffd5dc,b6e3f4
  parent: software-engineering
  children: []

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: abel
  tags:
    - tech-lead
spec:
  profile:
    displayName: Abel
    email: abel@airline.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [platform-team]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: backstage.user
  tags:
    - developer
spec:
  profile:
    displayName: Backstage User
    email: backstage.user@iberia.es
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Luna&backgroundColor=transparent
  memberOf: [platform-team]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ana
  tags:
    - developer
spec:
  profile:
    displayName: Ana
    email: ana@airline.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Leo&backgroundColor=transparent
  memberOf: [platform-team]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: estefanie
  tags:
    - developer
spec:
  profile:
    displayName: Estefanie
    email: estefanie@airline.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight&backgroundColor=transparent
  memberOf: [platform-team]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: zully
  tags:
    - business-analyst
spec:
  profile:
    displayName: Zully
    email: zully@airline.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight&backgroundColor=transparent
  memberOf: [platform-team]

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: luis
  tags:
    - product-owner
spec:
  profile:
    displayName: Luis
    email: luis@airline.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Midnight&backgroundColor=transparent
  memberOf: [platform-team]
