apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform
  description: Platform system
  tags:
    - idp
spec:
  owner: platform-team

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Backstage
  description: Backstage
  tags:
    - idp
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: platform